[book]
authors = ["dcorral"]
language = "en"
multilingual = false
src = "src"
title = "Docs"

[output.html]
git-repository-url = "https://github.com/dcorral/docs/tree/main/"
edit-url-template = "https://github.com/dcorral/docs/edit/main/{path}"
site-url = "/"
no-section-label = true
